/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from './IERC20.js';
export type { Ownable } from './Ownable.js';
export type { Pausable } from './Pausable.js';
export type { PresaleTimeWeeks } from './PresaleTimeWeeks.js';
export type { ReentrancyGuard } from './ReentrancyGuard.js';