/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PresaleTimeWeeksInterface extends Interface {
    getFunction(nameOrSignature: "MAX_TOKENS_WEI" | "appendWeekPrice" | "buy" | "closePresale" | "currentPriceUsdMicro" | "currentWeek" | "endTime" | "isActive" | "isPayToken" | "owner" | "pause" | "paused" | "priceForWeek" | "pricesLength" | "quote" | "setPayToken" | "setPriceForWeek" | "setTreasury" | "setWeekDuration" | "setWeekOverride" | "setWindow" | "startTime" | "totalSoldWei" | "transferOwnership" | "treasury" | "unpause" | "weekDuration" | "weekOverride" | "weekOverrideEnabled"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "Paused" | "PayTokenUpdated" | "PriceAppended" | "PriceSet" | "Purchased" | "TreasuryUpdated" | "Unpaused" | "WeekDurationUpdated" | "WeekOverrideUpdated" | "WindowUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'MAX_TOKENS_WEI', values?: undefined): string;
encodeFunctionData(functionFragment: 'appendWeekPrice', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'buy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'closePresale', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentPriceUsdMicro', values?: undefined): string;
encodeFunctionData(functionFragment: 'currentWeek', values?: undefined): string;
encodeFunctionData(functionFragment: 'endTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'isActive', values?: undefined): string;
encodeFunctionData(functionFragment: 'isPayToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceForWeek', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'pricesLength', values?: undefined): string;
encodeFunctionData(functionFragment: 'quote', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setPayToken', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'setPriceForWeek', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setWeekDuration', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWeekOverride', values: [boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setWindow', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'startTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalSoldWei', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'weekDuration', values?: undefined): string;
encodeFunctionData(functionFragment: 'weekOverride', values?: undefined): string;
encodeFunctionData(functionFragment: 'weekOverrideEnabled', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'MAX_TOKENS_WEI', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'appendWeekPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'closePresale', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentPriceUsdMicro', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'currentWeek', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isActive', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isPayToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceForWeek', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pricesLength', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'quote', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPayToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPriceForWeek', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWeekDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWeekOverride', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setWindow', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSoldWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weekDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weekOverride', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'weekOverrideEnabled', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [by: AddressLike];
      export type OutputTuple = [by: string];
      export interface OutputObject {by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PayTokenUpdatedEvent {
      export type InputTuple = [token: AddressLike, allowed: boolean];
      export type OutputTuple = [token: string, allowed: boolean];
      export interface OutputObject {token: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceAppendedEvent {
      export type InputTuple = [week: BigNumberish, priceUsdMicro: BigNumberish];
      export type OutputTuple = [week: bigint, priceUsdMicro: bigint];
      export interface OutputObject {week: bigint, priceUsdMicro: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PriceSetEvent {
      export type InputTuple = [week: BigNumberish, priceUsdMicro: BigNumberish];
      export type OutputTuple = [week: bigint, priceUsdMicro: bigint];
      export interface OutputObject {week: bigint, priceUsdMicro: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PurchasedEvent {
      export type InputTuple = [buyer: AddressLike, payToken: AddressLike, payAmount: BigNumberish, tokenAmountWei: BigNumberish, weekRef: BigNumberish, priceRef: BigNumberish];
      export type OutputTuple = [buyer: string, payToken: string, payAmount: bigint, tokenAmountWei: bigint, weekRef: bigint, priceRef: bigint];
      export interface OutputObject {buyer: string, payToken: string, payAmount: bigint, tokenAmountWei: bigint, weekRef: bigint, priceRef: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TreasuryUpdatedEvent {
      export type InputTuple = [oldTreasury: AddressLike, newTreasury: AddressLike];
      export type OutputTuple = [oldTreasury: string, newTreasury: string];
      export interface OutputObject {oldTreasury: string, newTreasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [by: AddressLike];
      export type OutputTuple = [by: string];
      export interface OutputObject {by: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WeekDurationUpdatedEvent {
      export type InputTuple = [oldDuration: BigNumberish, newDuration: BigNumberish];
      export type OutputTuple = [oldDuration: bigint, newDuration: bigint];
      export interface OutputObject {oldDuration: bigint, newDuration: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WeekOverrideUpdatedEvent {
      export type InputTuple = [enabled: boolean, week: BigNumberish];
      export type OutputTuple = [enabled: boolean, week: bigint];
      export interface OutputObject {enabled: boolean, week: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WindowUpdatedEvent {
      export type InputTuple = [startTime: BigNumberish, endTime: BigNumberish];
      export type OutputTuple = [startTime: bigint, endTime: bigint];
      export interface OutputObject {startTime: bigint, endTime: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PresaleTimeWeeks extends BaseContract {
    
    connect(runner?: ContractRunner | null): PresaleTimeWeeks;
    waitForDeployment(): Promise<this>;

    interface: PresaleTimeWeeksInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MAX_TOKENS_WEI: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    appendWeekPrice: TypedContractMethod<
      [priceMicro: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    buy: TypedContractMethod<
      [payToken: AddressLike, payAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    closePresale: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    currentPriceUsdMicro: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    currentWeek: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    endTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    isActive: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    isPayToken: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    priceForWeek: TypedContractMethod<
      [week: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    pricesLength: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    quote: TypedContractMethod<
      [payAmount: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    setPayToken: TypedContractMethod<
      [token: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setPriceForWeek: TypedContractMethod<
      [week: BigNumberish, priceMicro: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setWeekDuration: TypedContractMethod<
      [newDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setWeekOverride: TypedContractMethod<
      [enabled: boolean, week_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setWindow: TypedContractMethod<
      [newStartTime: BigNumberish, newEndTime: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    startTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    totalSoldWei: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    weekDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    weekOverride: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    weekOverrideEnabled: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MAX_TOKENS_WEI'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'appendWeekPrice'): TypedContractMethod<
      [priceMicro: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [payToken: AddressLike, payAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'closePresale'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'currentPriceUsdMicro'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'currentWeek'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'endTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'isActive'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'isPayToken'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'priceForWeek'): TypedContractMethod<
      [week: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pricesLength'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'quote'): TypedContractMethod<
      [payAmount: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setPayToken'): TypedContractMethod<
      [token: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPriceForWeek'): TypedContractMethod<
      [week: BigNumberish, priceMicro: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWeekDuration'): TypedContractMethod<
      [newDuration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWeekOverride'): TypedContractMethod<
      [enabled: boolean, week_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setWindow'): TypedContractMethod<
      [newStartTime: BigNumberish, newEndTime: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'totalSoldWei'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'weekDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weekOverride'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'weekOverrideEnabled'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'PayTokenUpdated'): TypedContractEvent<PayTokenUpdatedEvent.InputTuple, PayTokenUpdatedEvent.OutputTuple, PayTokenUpdatedEvent.OutputObject>;
getEvent(key: 'PriceAppended'): TypedContractEvent<PriceAppendedEvent.InputTuple, PriceAppendedEvent.OutputTuple, PriceAppendedEvent.OutputObject>;
getEvent(key: 'PriceSet'): TypedContractEvent<PriceSetEvent.InputTuple, PriceSetEvent.OutputTuple, PriceSetEvent.OutputObject>;
getEvent(key: 'Purchased'): TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;
getEvent(key: 'TreasuryUpdated'): TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
getEvent(key: 'WeekDurationUpdated'): TypedContractEvent<WeekDurationUpdatedEvent.InputTuple, WeekDurationUpdatedEvent.OutputTuple, WeekDurationUpdatedEvent.OutputObject>;
getEvent(key: 'WeekOverrideUpdated'): TypedContractEvent<WeekOverrideUpdatedEvent.InputTuple, WeekOverrideUpdatedEvent.OutputTuple, WeekOverrideUpdatedEvent.OutputObject>;
getEvent(key: 'WindowUpdated'): TypedContractEvent<WindowUpdatedEvent.InputTuple, WindowUpdatedEvent.OutputTuple, WindowUpdatedEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'PayTokenUpdated(address,bool)': TypedContractEvent<PayTokenUpdatedEvent.InputTuple, PayTokenUpdatedEvent.OutputTuple, PayTokenUpdatedEvent.OutputObject>;
      PayTokenUpdated: TypedContractEvent<PayTokenUpdatedEvent.InputTuple, PayTokenUpdatedEvent.OutputTuple, PayTokenUpdatedEvent.OutputObject>;
    

      'PriceAppended(uint32,uint256)': TypedContractEvent<PriceAppendedEvent.InputTuple, PriceAppendedEvent.OutputTuple, PriceAppendedEvent.OutputObject>;
      PriceAppended: TypedContractEvent<PriceAppendedEvent.InputTuple, PriceAppendedEvent.OutputTuple, PriceAppendedEvent.OutputObject>;
    

      'PriceSet(uint32,uint256)': TypedContractEvent<PriceSetEvent.InputTuple, PriceSetEvent.OutputTuple, PriceSetEvent.OutputObject>;
      PriceSet: TypedContractEvent<PriceSetEvent.InputTuple, PriceSetEvent.OutputTuple, PriceSetEvent.OutputObject>;
    

      'Purchased(address,address,uint256,uint256,uint256,uint256)': TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;
      Purchased: TypedContractEvent<PurchasedEvent.InputTuple, PurchasedEvent.OutputTuple, PurchasedEvent.OutputObject>;
    

      'TreasuryUpdated(address,address)': TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
      TreasuryUpdated: TypedContractEvent<TreasuryUpdatedEvent.InputTuple, TreasuryUpdatedEvent.OutputTuple, TreasuryUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    

      'WeekDurationUpdated(uint32,uint32)': TypedContractEvent<WeekDurationUpdatedEvent.InputTuple, WeekDurationUpdatedEvent.OutputTuple, WeekDurationUpdatedEvent.OutputObject>;
      WeekDurationUpdated: TypedContractEvent<WeekDurationUpdatedEvent.InputTuple, WeekDurationUpdatedEvent.OutputTuple, WeekDurationUpdatedEvent.OutputObject>;
    

      'WeekOverrideUpdated(bool,uint32)': TypedContractEvent<WeekOverrideUpdatedEvent.InputTuple, WeekOverrideUpdatedEvent.OutputTuple, WeekOverrideUpdatedEvent.OutputObject>;
      WeekOverrideUpdated: TypedContractEvent<WeekOverrideUpdatedEvent.InputTuple, WeekOverrideUpdatedEvent.OutputTuple, WeekOverrideUpdatedEvent.OutputObject>;
    

      'WindowUpdated(uint64,uint64)': TypedContractEvent<WindowUpdatedEvent.InputTuple, WindowUpdatedEvent.OutputTuple, WindowUpdatedEvent.OutputObject>;
      WindowUpdated: TypedContractEvent<WindowUpdatedEvent.InputTuple, WindowUpdatedEvent.OutputTuple, WindowUpdatedEvent.OutputObject>;
    
    };
  }