/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PresaleInterface extends Interface {
    getFunction(nameOrSignature: "buy" | "isAllowedToken" | "owner" | "priceUsdMicro" | "purchased" | "renounceOwnership" | "setPriceUsdMicro" | "setTreasury" | "setUSDC" | "setUSDT" | "totalSold" | "transferOwnership" | "treasury" | "usdc" | "usdt"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred" | "Purchase"): EventFragment;

    encodeFunctionData(functionFragment: 'buy', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'isAllowedToken', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'priceUsdMicro', values?: undefined): string;
encodeFunctionData(functionFragment: 'purchased', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setPriceUsdMicro', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTreasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUSDC', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'setUSDT', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'totalSold', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'usdt', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'buy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isAllowedToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'priceUsdMicro', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'purchased', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPriceUsdMicro', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTreasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUSDC', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setUSDT', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalSold', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdt', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PurchaseEvent {
      export type InputTuple = [buyer: AddressLike, payToken: AddressLike, payAmount: BigNumberish, tokenAmountOut: BigNumberish, priceUsdMicro: BigNumberish];
      export type OutputTuple = [buyer: string, payToken: string, payAmount: bigint, tokenAmountOut: bigint, priceUsdMicro: bigint];
      export interface OutputObject {buyer: string, payToken: string, payAmount: bigint, tokenAmountOut: bigint, priceUsdMicro: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Presale extends BaseContract {
    
    connect(runner?: ContractRunner | null): Presale;
    waitForDeployment(): Promise<this>;

    interface: PresaleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    buy: TypedContractMethod<
      [payToken: AddressLike, payAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >
    

    
    isAllowedToken: TypedContractMethod<
      [token: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    priceUsdMicro: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    purchased: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setPriceUsdMicro: TypedContractMethod<
      [newPriceUsdMicro: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setTreasury: TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUSDC: TypedContractMethod<
      [newUsdc: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    setUSDT: TypedContractMethod<
      [newUsdt: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    totalSold: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usdt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'buy'): TypedContractMethod<
      [payToken: AddressLike, payAmount: BigNumberish, ],
      [bigint],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isAllowedToken'): TypedContractMethod<
      [token: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'priceUsdMicro'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'purchased'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPriceUsdMicro'): TypedContractMethod<
      [newPriceUsdMicro: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTreasury'): TypedContractMethod<
      [newTreasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUSDC'): TypedContractMethod<
      [newUsdc: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setUSDT'): TypedContractMethod<
      [newUsdt: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'totalSold'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usdt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Purchase'): TypedContractEvent<PurchaseEvent.InputTuple, PurchaseEvent.OutputTuple, PurchaseEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Purchase(address,address,uint256,uint256,uint256)': TypedContractEvent<PurchaseEvent.InputTuple, PurchaseEvent.OutputTuple, PurchaseEvent.OutputObject>;
      Purchase: TypedContractEvent<PurchaseEvent.InputTuple, PurchaseEvent.OutputTuple, PurchaseEvent.OutputObject>;
    
    };
  }