/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface MerkleAirdropInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_WITHDRAW_DELAY" | "claim" | "claimed" | "endTime" | "merkleRoot" | "owner" | "renounceOwnership" | "rootFrozen" | "setMerkleRoot" | "start" | "startTime" | "started" | "sweep" | "token" | "transferOwnership"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed" | "MerkleRootSet" | "OwnershipTransferred" | "RootFrozen" | "Started" | "Swept"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_WITHDRAW_DELAY', values?: undefined): string;
encodeFunctionData(functionFragment: 'claim', values: [BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'claimed', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'endTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'merkleRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rootFrozen', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMerkleRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'start', values?: undefined): string;
encodeFunctionData(functionFragment: 'startTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'started', values?: undefined): string;
encodeFunctionData(functionFragment: 'sweep', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_WITHDRAW_DELAY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'endTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rootFrozen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'start', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'started', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sweep', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [account: AddressLike, amount: BigNumberish];
      export type OutputTuple = [account: string, amount: bigint];
      export interface OutputObject {account: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MerkleRootSetEvent {
      export type InputTuple = [root: BytesLike];
      export type OutputTuple = [root: string];
      export interface OutputObject {root: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RootFrozenEvent {
      export type InputTuple = [root: BytesLike];
      export type OutputTuple = [root: string];
      export interface OutputObject {root: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StartedEvent {
      export type InputTuple = [at: BigNumberish];
      export type OutputTuple = [at: bigint];
      export interface OutputObject {at: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SweptEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MerkleAirdrop extends BaseContract {
    
    connect(runner?: ContractRunner | null): MerkleAirdrop;
    waitForDeployment(): Promise<this>;

    interface: MerkleAirdropInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_WITHDRAW_DELAY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [amount: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    claimed: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    endTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    merkleRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rootFrozen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setMerkleRoot: TypedContractMethod<
      [newRoot: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    start: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    startTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    started: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    sweep: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_WITHDRAW_DELAY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [amount: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimed'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'endTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'merkleRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rootFrozen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setMerkleRoot'): TypedContractMethod<
      [newRoot: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'start'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'started'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'sweep'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'MerkleRootSet'): TypedContractEvent<MerkleRootSetEvent.InputTuple, MerkleRootSetEvent.OutputTuple, MerkleRootSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RootFrozen'): TypedContractEvent<RootFrozenEvent.InputTuple, RootFrozenEvent.OutputTuple, RootFrozenEvent.OutputObject>;
getEvent(key: 'Started'): TypedContractEvent<StartedEvent.InputTuple, StartedEvent.OutputTuple, StartedEvent.OutputObject>;
getEvent(key: 'Swept'): TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;

    filters: {
      
      'Claimed(address,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'MerkleRootSet(bytes32)': TypedContractEvent<MerkleRootSetEvent.InputTuple, MerkleRootSetEvent.OutputTuple, MerkleRootSetEvent.OutputObject>;
      MerkleRootSet: TypedContractEvent<MerkleRootSetEvent.InputTuple, MerkleRootSetEvent.OutputTuple, MerkleRootSetEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RootFrozen(bytes32)': TypedContractEvent<RootFrozenEvent.InputTuple, RootFrozenEvent.OutputTuple, RootFrozenEvent.OutputObject>;
      RootFrozen: TypedContractEvent<RootFrozenEvent.InputTuple, RootFrozenEvent.OutputTuple, RootFrozenEvent.OutputObject>;
    

      'Started(uint64)': TypedContractEvent<StartedEvent.InputTuple, StartedEvent.OutputTuple, StartedEvent.OutputObject>;
      Started: TypedContractEvent<StartedEvent.InputTuple, StartedEvent.OutputTuple, StartedEvent.OutputObject>;
    

      'Swept(address,uint256)': TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
      Swept: TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
    
    };
  }