/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface PresaleVestingMerkleInterface extends Interface {
    getFunction(nameOrSignature: "ADMIN_WITHDRAW_DELAY" | "DECIMALS" | "DURATION" | "DURATION_MONTHS" | "MONTH" | "activateAndClaim" | "activateMerkle" | "addInvestorHuman" | "addInvestorsHuman" | "adminAllocationWei" | "claim" | "claimableWei" | "claimedWei" | "fund" | "getAccountInfo" | "merkleActivated" | "merkleAllocationWei" | "merkleRoot" | "monthsElapsed" | "nextUnlockAt" | "owner" | "renounceOwnership" | "rootFrozen" | "setMerkleRoot" | "start" | "startTime" | "started" | "sweep" | "token" | "totalAllocationWei" | "transferOwnership" | "vestedWei"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Claimed" | "Funded" | "InvestorAdded" | "MerkleActivated" | "MerkleRootSet" | "OwnershipTransferred" | "RootFrozen" | "Started" | "Swept"): EventFragment;

    encodeFunctionData(functionFragment: 'ADMIN_WITHDRAW_DELAY', values?: undefined): string;
encodeFunctionData(functionFragment: 'DECIMALS', values?: undefined): string;
encodeFunctionData(functionFragment: 'DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'DURATION_MONTHS', values?: undefined): string;
encodeFunctionData(functionFragment: 'MONTH', values?: undefined): string;
encodeFunctionData(functionFragment: 'activateAndClaim', values: [BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'activateMerkle', values: [BigNumberish, BytesLike[]]): string;
encodeFunctionData(functionFragment: 'addInvestorHuman', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'addInvestorsHuman', values: [AddressLike[], BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'adminAllocationWei', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claim', values?: undefined): string;
encodeFunctionData(functionFragment: 'claimableWei', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'claimedWei', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'fund', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getAccountInfo', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'merkleActivated', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'merkleAllocationWei', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'merkleRoot', values?: undefined): string;
encodeFunctionData(functionFragment: 'monthsElapsed', values?: undefined): string;
encodeFunctionData(functionFragment: 'nextUnlockAt', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'rootFrozen', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMerkleRoot', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'start', values?: undefined): string;
encodeFunctionData(functionFragment: 'startTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'started', values?: undefined): string;
encodeFunctionData(functionFragment: 'sweep', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'token', values?: undefined): string;
encodeFunctionData(functionFragment: 'totalAllocationWei', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'vestedWei', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'ADMIN_WITHDRAW_DELAY', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DECIMALS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'DURATION_MONTHS', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'MONTH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activateAndClaim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'activateMerkle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addInvestorHuman', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addInvestorsHuman', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'adminAllocationWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimableWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimedWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAccountInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleActivated', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleAllocationWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'merkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'monthsElapsed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nextUnlockAt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rootFrozen', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMerkleRoot', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'start', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'startTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'started', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'sweep', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'totalAllocationWei', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'vestedWei', data: BytesLike): Result;
  }

  
    export namespace ClaimedEvent {
      export type InputTuple = [account: AddressLike, amountWei: BigNumberish, totalClaimedWei: BigNumberish];
      export type OutputTuple = [account: string, amountWei: bigint, totalClaimedWei: bigint];
      export interface OutputObject {account: string, amountWei: bigint, totalClaimedWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace FundedEvent {
      export type InputTuple = [from: AddressLike, amountWei: BigNumberish];
      export type OutputTuple = [from: string, amountWei: bigint];
      export interface OutputObject {from: string, amountWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InvestorAddedEvent {
      export type InputTuple = [account: AddressLike, addedWei: BigNumberish];
      export type OutputTuple = [account: string, addedWei: bigint];
      export interface OutputObject {account: string, addedWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MerkleActivatedEvent {
      export type InputTuple = [account: AddressLike, totalWei: BigNumberish];
      export type OutputTuple = [account: string, totalWei: bigint];
      export interface OutputObject {account: string, totalWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MerkleRootSetEvent {
      export type InputTuple = [root: BytesLike];
      export type OutputTuple = [root: string];
      export interface OutputObject {root: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RootFrozenEvent {
      export type InputTuple = [root: BytesLike];
      export type OutputTuple = [root: string];
      export interface OutputObject {root: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StartedEvent {
      export type InputTuple = [at: BigNumberish];
      export type OutputTuple = [at: bigint];
      export interface OutputObject {at: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SweptEvent {
      export type InputTuple = [to: AddressLike, amountWei: BigNumberish];
      export type OutputTuple = [to: string, amountWei: bigint];
      export interface OutputObject {to: string, amountWei: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface PresaleVestingMerkle extends BaseContract {
    
    connect(runner?: ContractRunner | null): PresaleVestingMerkle;
    waitForDeployment(): Promise<this>;

    interface: PresaleVestingMerkleInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    ADMIN_WITHDRAW_DELAY: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DECIMALS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    DURATION_MONTHS: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    MONTH: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    activateAndClaim: TypedContractMethod<
      [totalTokensHuman: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    activateMerkle: TypedContractMethod<
      [totalTokensHuman: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >
    

    
    addInvestorHuman: TypedContractMethod<
      [account: AddressLike, amountTokens: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    addInvestorsHuman: TypedContractMethod<
      [accounts: AddressLike[], amountTokens: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    adminAllocationWei: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    claim: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    claimableWei: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    claimedWei: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    fund: TypedContractMethod<
      [amountWei: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getAccountInfo: TypedContractMethod<
      [account: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {totalWei: bigint, vestedNowWei: bigint, claimedSoFarWei: bigint, claimableNowWei: bigint, monthsElapsedNow: bigint, nextUnlockTimestamp: bigint }],
      'view'
    >
    

    
    merkleActivated: TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    merkleAllocationWei: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    merkleRoot: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    monthsElapsed: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    nextUnlockAt: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    rootFrozen: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    setMerkleRoot: TypedContractMethod<
      [newRoot: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    start: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    startTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    started: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    sweep: TypedContractMethod<
      [to: AddressLike, amountWei: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    totalAllocationWei: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    vestedWei: TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'ADMIN_WITHDRAW_DELAY'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DECIMALS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'DURATION_MONTHS'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'MONTH'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'activateAndClaim'): TypedContractMethod<
      [totalTokensHuman: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'activateMerkle'): TypedContractMethod<
      [totalTokensHuman: BigNumberish, proof: BytesLike[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addInvestorHuman'): TypedContractMethod<
      [account: AddressLike, amountTokens: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addInvestorsHuman'): TypedContractMethod<
      [accounts: AddressLike[], amountTokens: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'adminAllocationWei'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claim'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimableWei'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'claimedWei'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'fund'): TypedContractMethod<
      [amountWei: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAccountInfo'): TypedContractMethod<
      [account: AddressLike, ],
      [[bigint, bigint, bigint, bigint, bigint, bigint] & {totalWei: bigint, vestedNowWei: bigint, claimedSoFarWei: bigint, claimableNowWei: bigint, monthsElapsedNow: bigint, nextUnlockTimestamp: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'merkleActivated'): TypedContractMethod<
      [arg0: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'merkleAllocationWei'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'merkleRoot'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'monthsElapsed'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'nextUnlockAt'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'rootFrozen'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setMerkleRoot'): TypedContractMethod<
      [newRoot: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'start'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'startTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'started'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'sweep'): TypedContractMethod<
      [to: AddressLike, amountWei: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'totalAllocationWei'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'vestedWei'): TypedContractMethod<
      [account: AddressLike, ],
      [bigint],
      'view'
    >;

    getEvent(key: 'Claimed'): TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
getEvent(key: 'Funded'): TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
getEvent(key: 'InvestorAdded'): TypedContractEvent<InvestorAddedEvent.InputTuple, InvestorAddedEvent.OutputTuple, InvestorAddedEvent.OutputObject>;
getEvent(key: 'MerkleActivated'): TypedContractEvent<MerkleActivatedEvent.InputTuple, MerkleActivatedEvent.OutputTuple, MerkleActivatedEvent.OutputObject>;
getEvent(key: 'MerkleRootSet'): TypedContractEvent<MerkleRootSetEvent.InputTuple, MerkleRootSetEvent.OutputTuple, MerkleRootSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'RootFrozen'): TypedContractEvent<RootFrozenEvent.InputTuple, RootFrozenEvent.OutputTuple, RootFrozenEvent.OutputObject>;
getEvent(key: 'Started'): TypedContractEvent<StartedEvent.InputTuple, StartedEvent.OutputTuple, StartedEvent.OutputObject>;
getEvent(key: 'Swept'): TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;

    filters: {
      
      'Claimed(address,uint256,uint256)': TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
      Claimed: TypedContractEvent<ClaimedEvent.InputTuple, ClaimedEvent.OutputTuple, ClaimedEvent.OutputObject>;
    

      'Funded(address,uint256)': TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
      Funded: TypedContractEvent<FundedEvent.InputTuple, FundedEvent.OutputTuple, FundedEvent.OutputObject>;
    

      'InvestorAdded(address,uint256)': TypedContractEvent<InvestorAddedEvent.InputTuple, InvestorAddedEvent.OutputTuple, InvestorAddedEvent.OutputObject>;
      InvestorAdded: TypedContractEvent<InvestorAddedEvent.InputTuple, InvestorAddedEvent.OutputTuple, InvestorAddedEvent.OutputObject>;
    

      'MerkleActivated(address,uint256)': TypedContractEvent<MerkleActivatedEvent.InputTuple, MerkleActivatedEvent.OutputTuple, MerkleActivatedEvent.OutputObject>;
      MerkleActivated: TypedContractEvent<MerkleActivatedEvent.InputTuple, MerkleActivatedEvent.OutputTuple, MerkleActivatedEvent.OutputObject>;
    

      'MerkleRootSet(bytes32)': TypedContractEvent<MerkleRootSetEvent.InputTuple, MerkleRootSetEvent.OutputTuple, MerkleRootSetEvent.OutputObject>;
      MerkleRootSet: TypedContractEvent<MerkleRootSetEvent.InputTuple, MerkleRootSetEvent.OutputTuple, MerkleRootSetEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'RootFrozen(bytes32)': TypedContractEvent<RootFrozenEvent.InputTuple, RootFrozenEvent.OutputTuple, RootFrozenEvent.OutputObject>;
      RootFrozen: TypedContractEvent<RootFrozenEvent.InputTuple, RootFrozenEvent.OutputTuple, RootFrozenEvent.OutputObject>;
    

      'Started(uint64)': TypedContractEvent<StartedEvent.InputTuple, StartedEvent.OutputTuple, StartedEvent.OutputObject>;
      Started: TypedContractEvent<StartedEvent.InputTuple, StartedEvent.OutputTuple, StartedEvent.OutputObject>;
    

      'Swept(address,uint256)': TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
      Swept: TypedContractEvent<SweptEvent.InputTuple, SweptEvent.OutputTuple, SweptEvent.OutputObject>;
    
    };
  }